version: '3'

services:
  ms_catalogo_frontend:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - ms-catalog
      - inte-rabbitmq_codeflix_rabbitmq

  ms_catalog_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    volumes:
      - ./.data/elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ms-catalog

  ms_catalog_kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      - ELASTICSEARCH_HOSTS=http://ms_catalog_es:9200
    ports:
      - 5601:5601
    networks:
      - ms-catalog

networks:
  ms-catalog:
    driver: bridge
  inte-rabbitmq_codeflix_rabbitmq:
    external: true
